# Generated by Django 2.1.1 on 2019-06-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papeleria', '0002_auto_20190611_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
