# Generated by Django 2.1.1 on 2019-06-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papeleria', '0003_compra_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
